name: Build & Deploy to Github Pages
on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'

jobs:
  unit:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Clean install dependencies and run tests
      run: |
        npm ci --silent
        CI=true npm test
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: unit
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: 'Ann Cudis'
      GITHUB_EMAIL: 'jvcudis@gmail.com'
    steps:
    - uses: actions/checkout@master
    - uses: ./actions/build-deploy
  integration:
    name: Run Integration Test
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@master
    - name: Run Cypress integraton tests
      run: |
        npm install cypress --save-dev
        CI=true CYPRESS_BUILDENV=prod npm run test:integration
