name: Build & Deploy to Github Pages
on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, edited, reopened]

jobs:
  build:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Clean install dependencies and run tests
      run: |
        npm ci --silent
        CI=true npm test
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: 'Ann Cudis'
      GITHUB_EMAIL: 'jvcudis@gmail.com'
    steps:
    - uses: actions/checkout@master
    - uses: ./actions/build-deploy
