name: Build & Deploy to Github Pages
on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'

jobs:
  unit:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Clean install dependencies and run tests
      run: |
        npm ci --silent
        CI=true npm test
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: unit
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: 'Ann Cudis'
      GITHUB_EMAIL: 'jvcudis@gmail.com'
    steps:
    - uses: actions/checkout@master
    - name: Build static site and deploy to gh-pages
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_EMAIL}"
        git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        npm ci --silent
        npm run deploy
        # Trigger a page build to avoid issues in deployment
        curl -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: Accept: application/vnd.github.v3+json" \
          -X POST https://api.github.com/repos/${GITHUB_REPOSITORY}/pages/builds
  integration:
    name: Run Integration Test
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@master
    - name: Run Cypress integraton tests
      run: |
        npm install cypress --save-dev
        CI=true CYPRESS_BUILDENV=prod npm run test:integration
