name: Build & Deploy to Github Pages
on: [push]

jobs:
  build:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./actions/execute-test
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./actions/build-deploy
