name: Continuous Integration
on:
  pull_request:
    paths-ignore:
    - 'README.md'

jobs:
  build:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Clean install dependencies and run tests
      run: |
        npm ci --silent
        CI=true npm test
